#! /usr/bin/env python
# -*- coding: utf-8 -*-
import vk_api
from vk_api.bot_longpoll import VkBotLongPoll
from vk_api.utils import get_random_id

vk = vk_api.VkApi(token='3709764b230f73dbf6a6fca9c41e726af8c0e28eff5ea171f2e25d6b5d3761711e9cf46b77cbf3d7c47ba')  #токен паблика

class MyVkLongPoll(VkBotLongPoll):                      # создаю класс чтобы он не терял соединение с сервером вк когда тот  перезагружается (перезагружается раз в день где-то глубоко ночью)
        def listen(self):
            while True:
                try:
                    for event in self.check():
                        yield event
                except Exception as e:
                        print(e)            #будет писать в консоль что таймаут произошел, при желании просто впишите сюда pass

bot_id = '193179464'      # сюда id паблика
longpoll = MyVkLongPoll(vk, bot_id)

def send_message(msg):
    vk.method('messages.send',{'random_id':get_random_id(),'peer_id':event.obj.peer_id,'message':msg})

for event in longpoll.listen():     #начинаем слушать лонгпулл
    if event.obj:
        if event.obj.text.lower() == 'команды':
            send_message('Я не имею команд')
            print(event.obj.text)
# vk.method('сам метод',{параметры метода})

